name: Quality Test
on:
  push:
    branches:
       DEV

jobs:
  flake8:
    runs-on: window
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r requirement.txt
