FROM python:3.8-slim
# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Expose the port the app runs on
EXPOSE 8080

# Define environment variables
ENV FLASK_VAR=app.py
ENV FLASK_HOST=0.0.0.0

# Run the application
CMD ["flask", "run"]
